#!/bin/bash
echo "linkedin-post-writer loaded. Skills available:"
echo "  linkedin-gen — end-to-end orchestrator (brief → convert/carousel → validate → schedule)"
echo "  linkedin-brief — blog → brief JSON (format decision + hook + pillar)"
echo "  linkedin-convert — brief+blog → native text post (1100-1300 chars, 3-5 hashtags)"
echo "  linkedin-carousel — brief+blog → 7-10 slide JSON (1080x1350, mobile-safe zones)"
echo "  linkedin-validate — Depth Score 0-100 gate with hard-fail rules"
echo "  linkedin-schedule — backend bridge to POST draft to /api/automation/linkedin/{id}/schedule"
echo ""
echo "Agent available:"
echo "  linkedin-writer — subagent for batch LinkedIn conversion across multiple blog posts"
echo ""
echo "REMINDER: Read references/compiled/refs-linkedin-*.md via --append-system-prompt-file for skill runs."
echo "REMINDER: Depth Score >=80 threshold is hard gate. AI slop phrases are auto-fail."
